import type { ThemeTokens } from './theme.types'

export const createThemeCustomProperties = (
  tokens: ThemeTokens,
): Record<`--${string}`, string> => ({
  '--color-primary': tokens.colors.primary,
  '--color-secondary': tokens.colors.secondary,
  '--color-background': tokens.colors.background,
  '--color-surface': tokens.colors.surface,
  '--color-surface-elevated': tokens.colors.surfaceElevated,
  '--color-text': tokens.colors.text,
  '--color-text-muted': tokens.colors.textMuted,
  '--color-border': tokens.colors.border,
  '--color-success': tokens.colors.success,
  '--color-warning': tokens.colors.warning,
  '--color-danger': tokens.colors.danger,
  '--font-family-body': tokens.typography.fontFamily,
  '--font-family-display': tokens.typography.displayFontFamily,
  '--font-size-base': `${tokens.typography.baseSize}px`,
  '--line-height-body': String(tokens.typography.lineHeight),
  '--font-weight-heading': String(tokens.typography.headingWeight),
  '--font-weight-body': String(tokens.typography.bodyWeight),
  '--radius-sm': `${tokens.radius.small}px`,
  '--radius-md': `${tokens.radius.medium}px`,
  '--radius-lg': `${tokens.radius.large}px`,
  '--radius-pill': `${tokens.radius.pill}px`,
  '--space-unit': `${tokens.spacing.baseUnit * tokens.spacing.density}px`,
  '--control-height': `${tokens.controls.height}px`,
  '--control-border-width': `${tokens.controls.borderWidth}px`,
  '--focus-ring-width': `${tokens.controls.focusRingWidth}px`,
  '--shadow-color': tokens.shadows.color,
  '--shadow-opacity': String(tokens.shadows.opacity),
  '--shadow-blur': `${tokens.shadows.blur}px`,
  '--shadow-spread': `${tokens.shadows.spread}px`,
  '--shadow-offset-y': `${tokens.shadows.offsetY}px`,
})
